miama_events = [
    [-7.00, "Govt increases morgage interest rate."],
    [-37.69, "Flooding of lower areas."],
    [-34.57, "Student loan deadlines get delayed by 10 months."],
    [-31.30, "Increased tourism."],
    [-33.36, "New wave of COVID-19."],
    [-37.36, "Shooting at casino."],
    [-41.75, "Soft market crash."],
    [-36.50, "US makes trade deals with Japan, India, and Taiwan."],
    [-32.06, "National Infrustructure bill passed. "],
    [-28.66, "Stock market surge."],
    [-35.08, "Wood plank shortage."],
    [-31.19, "Demand for housing increases."],
    [-27.06, "Stock market surge."],
    [-21.95, "New casino built."],
    [-18.83, "Q4 ends, consumers confident about market."],
    [-6.66, "Gas prices drop."],
    [-10.39, "Stock market crash"],
    [-21.14, "Concrete prices spike"]
]

nyc_events =[
    [-7.00, "Gov't increases morgage interest rate."],
    [-4.21, "Mayor approves bill to expand subway lines"],
    [0.58, "Student loan deadlines get delayed by 10 months."],
    [5.61, "New bill approved to build new skyscraper "],
    [0.33, "Increasing crime rates "],
    [6.35, "Mayor makes city more walkable and green"],
    [3.16, "New wave of COVID-19."],
    [-4.06, "Soft market crash."],
    [4.57, "US makes trade deals with Japan, India, and Taiwan."],
    [-11.12, "Study shows people are more likely to be depressed in city."],
    [-16.45, "Sellers' market "],
    [-10.60, "National Infrustructure bill passed."],
    [-6.13, "Stock market surge."],
    [-14.58, "Wood plank shortage."],
    [-17.14, "Skyscraper project halted, contruction equipment stranded"],
    [-7.20, "New companies move into nyc "],
    [-1.63, "Stock market surge."],
    [2.31, "Q4 ends, consumers confident about market."],
    [17.65, "Gas prices drop."],
    [8.24, "traffic at an all time high"],
    [12.95, "Stock market crash"],
    [-0.61, "Stock market crash"]
]

weston_events = [
    [-7.00, "Gov't increases morgage interest rate. "],
    [-2.35, "Student loan deadlines get delayed by 10 months."],
    [-5.28, "New wave of COVID-19."],
    [-9.54, "Drought"],
    [-15.87, "Soft market crash."],
    [-8.30, "US makes trade deals with Japan, India, and Taiwan. "],
    [-1.88, "National Infrustructure bill passed. "],
    [3.02,  "Stock market surge."],
    [-6.25, "Wood plank shortage."] ,
    [-10.00,"Companies enter weston to cut down trees "],
    [-4.60, "Stock market surge."],
    [-17.96, "Overpriced housing market "],
    [-20.42, "School staff shortage."],
    [-17.23, "Q4 ends, consumers confident about market."],
    [-4.82, "Gas prices drop."],
    [-8.63, "Stock market crash"],
    [-19.59, "Concrete prices spike"],
    [4.53,  "increased buyers in market "]
]

la_events = [
    [-7.00, "Gov't increases morgage interest rate. "],
    [-30.25, "Wildfire"],
    [-26.76, "Student loan deadlines get delayed by 10 months."],
    [-20.17, "minimum wage increase"],
    [-14.58, "Real estate tv shows increase la housing market"],
    [-17.15, "New wave of COVID-19."],
    [-7.20, "LA Schools climb up rankings "],
    [-13.70, "Soft market crash."],
    [-5.93, "US makes trade deals with Japan, India, and Taiwan. "],
    [0.65, "National Infrustructure bill passed. "],
    [5.69, "Stock market surge."],
    [16.25, "big real estate developers enter LA"],
    [-9.11, "Wood plank shortage."],
    [-3.66, "Stock market surge."],
    [0.20, "Q4 ends, consumers confident about market."],
    [15.23, "Gas prices drop."],
    [10.62, "Stock market crash"],
    [-2.66, "Concrete prices spike"]
]


atlanta_events = [
    [-7.00, "Gov't increases morgage interest rate. "],
    [2.30, "Increase in housing market"],
    [7.41, "Student loan deadlines get delayed by 10 months."],
    [2.04, "Hypothetical liberal uprising."],
    [-1.02, "New wave of COVID-19."],
    [4.92, "School doing better."],
    [-2.42, "Soft market crash."],
    [6.36, "US makes trade deals with Japan, India, and Taiwan. "],
    [13.80, "National Infrustructure bill passed. "],
    [19.49, "Stock market surge."],
    [25.47, "Mayor dies."],
    [14.18, "Wood plank shortage."],
    [21.03, "Stock market surge."],
    [25.87, "Q4 ends, consumers confident about market."],
    [44.75, "Gas prices drop."],
    [38.96, "Stock market crash"],
    [22.28, "Concrete prices spike"]
]

greatneck_events = [
    [-7.00, "Gov't increases morgage interest rate. "],
    [-2.35, "Student loan deadlines get delayed by 10 months."],
    [14.25, "ranked best school in ny "],
    [-5.28, "New wave of COVID-19."],
    [-11.91,"Soft market crash."],
    [-3.98, "US makes trade deals with Japan, India, and Taiwan. "],
    [2.74, "National Infrustructure bill passed. "],
    [13.01, "more buyers enter market "],
    [7.88, "Stock market surge."],
    [-1.83, "Wood plank shortage."],
    [-5.76, "Lab explosion in school"],
    [4.06, "Stock market surge."],
    [8.22, "Q4 ends, consumers confident about market."],
    [24.45, "Gas prices drop."],
    [19.47, "Stock market crash"],
    [5.14, "Concrete prices spike"],
]